### ISSUE TITLE
couldn't find file 'jquery.Lazy-images'

### ISSUE THREAD

**Issue by ajbraus** [singlebrook/jquery-lazy-images#13]
couldn't find file 'jquery.Lazy-images'

also tried jquery.lazy-images and others.

I also already restarted my server.

Your docs say add //= require . . . to both the .css and .js application files. That can't be right because one is *= ... and the other is //= . . .

**Comment by sbleon** [comment]
@ajbraus, you can see how it's set up in the testing app in spec/dummy.
[application.js](https://github.com/singlebrook/jquery-lazy-images/blob/master/spec/dummy/app/assets/javascripts/application.js#L16)
[application.css](https://github.com/singlebrook/jquery-lazy-images/blob/master/spec/dummy/app/assets/stylesheets/application.css#L13)

I've just pushed an update to [the README](https://github.com/singlebrook/jquery-lazy-images/blob/master/README.md) that improves the setup instructions. Please take another look at it and let me know if that helps resolve your issue.

**Comment by sbleon** [comment]
@ajbraus I'm running into the same issue today in a Rails 3.1 app. I'll let you know when I figure it out.

**Comment by sbleon** [comment]
@ajbraus, looks like my fix worked. Please try 0.2.3. Thanks!
