### ISSUE TITLE
Support for Rails 4.0

### ISSUE THREAD

**Issue by urzur** [singlebrook/jquery-lazy-images#15]
Running Rails 4 and when doing bundle install get the following error:
![selection_026](https://f.cloud.github.com/assets/1127245/2003154/9b373e9a-8634-11e3-9a89-0d330b5a61d0.png)

![selection_027](https://f.cloud.github.com/assets/1127245/2003161/c7d30bfa-8634-11e3-8d50-43c2154aaea6.png)

**Comment by sbleon** [comment]
That is very odd! The [gemspec states that it requires Rails 3.1+](https://github.com/singlebrook/jquery-lazy-images/blob/master/jquery-lazy-images.gemspec#L18).
Are you using a fork? What does the line say in your `Gemfile` about
jquery-lazy-images?

**Comment by sbleon** [comment]
@urzur I've just released a new version (0.3.0) that includes Rails 4 support. Please try updating. Thanks!
